### ISSUE TITLE
Add support to SimpleModel serialization

### ISSUE THREAD

**Issue by lamenezes** [lamenezes/simple-model#2]
Sometimes using `dict(model)` isn't enough to suit serialization needs. It would be nice to have a simple serializer to do such:

```python
>>> data = {'foo': 123, 'bar': 456, 'baz': 789}
>>> model = DynamicModel(**data)
>>> class SimpleSerializer:
...    fields = ('foo', 'baz')  # do not serialize Model.bar
>>> serializer = SimpleSerializer(model)
>>> serializer.serialize()
{'foo': 123, 'baz': 789}
```

In the future this class can be used to perform actual serialization (not only dict conversion) for types like json, xml etc.

**Comment by Marlysson** [comment]
Is just create a serializer class that receives a model, and look at `fields ` attribute and after compare with attributes from model received by the serializer class? Returning the fields converted...

**Comment by lamenezes** [comment]
Yes, @Marlysson. That's preety much it.

**Comment by Marlysson** [comment]
@lamenezes The serializer class need define an attribute called `model` that return the attributes's model related?

Or is really need just the `fields` attribute receiving a json content?

**Comment by lamenezes** [comment]
The `serialize` method use the `fields` defined in the seriaizer class (i.e. `Serializer.fields`) and the `model` to perform the serialization. Something like:

```python
class Serializer:
    fields = ('a', 'b', 'c')
   
    def __init__(self, model):
        self.model = model

    def serialize(self):
        # use self.fields and self.model to perform serialization
```

**Comment by lamenezes** [comment]
This feature is not going in :v
