### ISSUE TITLE
Fix model.as_dict when model has enum attribute

### ISSUE THREAD

**Issue by beatrizuezu** [lamenezes/simple-model#36]
When using enum attribute and use model.as_dict(), the enum attribute value doesn't is converted appropriately:

![Captura de Tela 2019-06-13 às 18 55 59](https://user-images.githubusercontent.com/5013052/59470043-f30d5600-8e0c-11e9-82f1-b08712afbfa0.png)

I guess .as_dict() should return this:

`{'bar': 'bar', 'foo':'foo'}`

**Comment by lamenezes** [comment]
Fixed on PR #37
